import React from 'react';
import { 
  LayoutDashboard, 
  Briefcase, 
  FileText, 
  Calendar, 
  HardHat, 
  ShieldCheck, 
  ShieldAlert, 
  Files, 
  DollarSign, 
  Clock, 
  Activity,
  Settings 
} from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    projects: 'Projects',
    contracts: 'Contracts',
    planning: 'Planning',
    siteManagement: 'Site Management',
    quality: 'Quality Control',
    safety: 'Safety (HSE)',
    documents: 'Documents',
    costs: 'Costs & Resources',
    timesheets: 'Timesheets',
    audit: 'Audit Trail',
    settings: 'Settings',
    totalBudget: 'Total Budget',
    activeProjects: 'Active Projects',
    overallProgress: 'Overall Progress',
    safetyIncidents: 'Safety Incidents',
    projectName: 'Project Name',
    status: 'Status',
    budget: 'Budget',
    progress: 'Progress',
    recentReports: 'Recent Daily Reports',
    addProject: 'Add New Project',
    search: 'Search...',
    ncrTracking: 'NCR Tracking',
    openIncidents: 'Open Incidents',
    upcomingMilestones: 'Upcoming Milestones',
    language: 'Language',
    welcomeBack: "Welcome back. Here's what's happening today.",
    generateReport: 'Generate Report',
    vsLastMonth: 'vs last month',
    progressPerProject: 'Progress per Project (%)',
    projectDistribution: 'Project Distribution',
    completed: 'Completed',
    active: 'Active',
    onHold: 'On Hold',
    activeProjectsStatus: 'Active Projects Status',
    viewAll: 'View All',
    filter: 'Filter',
    allocatedBudget: 'Allocated Budget',
    exportSchedule: 'Export Schedule',
    baseline: 'Master Schedule Baseline',
    criticalPath: 'Critical Path',
    activityDescription: 'Activity Description',
    newDailyReport: 'New Daily Report',
    siteActivityLog: 'Site Activity Log',
    totalLabor: 'Total Labor',
    equipment: 'Equipment',
    deliveries: 'Deliveries',
    ongoingActivities: 'Ongoing Activities',
    sitePhotos: 'Site Photos',
    viewPhoto: 'VIEW PHOTO',
    pendingApprovals: 'Pending Approvals',
    approve: 'Approve',
    review: 'Review',
    createContract: 'Create Contract',
    contractSummary: 'Main Contract Summary',
    contractValue: 'Contract Value',
    duration: 'Duration',
    variationsClaims: 'Variations & Claims',
    newInspection: 'New Inspection',
    ncrId: 'NCR ID',
    description: 'Description',
    severity: 'Severity',
    dateOpened: 'Date Opened',
    reportIncident: 'Report Incident',
    safeWorkingDays: 'Safe Working Days',
    ltis: 'LTIs (Lost Time Injuries)',
    toolboxTalks: 'Toolbox Talks This Month',
    recentSafetyObs: 'Recent Safety Observations',
    safetyPerformance: 'Safety Performance (LTI Frequency Rate)',
    frequencyRate: 'Frequency Rate',
    targetRate: 'Target Rate',
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    docTitle: 'Document Title',
    docCode: 'Document Code',
    version: 'Version',
    date: 'Date',
    actions: 'Actions',
    actualCost: 'Actual Cost',
    plannedCost: 'Planned Cost',
    variance: 'Variance',
    employee: 'Employee',
    hours: 'Hours',
    save: 'Save',
    cancel: 'Cancel',
    projectCode: 'Project Code',
    startDate: 'Start Date',
    endDate: 'End Date',
    userManagement: 'User Management',
    role: 'Role',
    email: 'Email',
    addNew: 'Add New',
    high: 'High',
    medium: 'Medium',
    low: 'Low'
  },
  ar: {
    dashboard: 'لوحة القيادة',
    projects: 'المشاريع',
    contracts: 'العقود',
    planning: 'التخطيط',
    siteManagement: 'إدارة الموقع',
    quality: 'ضبط الجودة',
    safety: 'السلامة (HSE)',
    documents: 'المستندات',
    costs: 'التكاليف والموارد',
    timesheets: 'الجداول الزمنية',
    audit: 'سجل النشاطات',
    settings: 'الإعدادات',
    totalBudget: 'إجمالي الميزانية',
    activeProjects: 'المشاريع النشطة',
    overallProgress: 'التقدم العام',
    safetyIncidents: 'حوادث السلامة',
    projectName: 'اسم المشروع',
    status: 'الحالة',
    budget: 'الميزانية',
    progress: 'التقدم',
    recentReports: 'التقارير اليومية الأخيرة',
    addProject: 'إضافة مشروع جديد',
    search: 'بحث...',
    ncrTracking: 'تتبع NCR',
    openIncidents: 'حوادث مفتوحة',
    upcomingMilestones: 'المعالم القادمة',
    language: 'اللغة',
    welcomeBack: 'مرحباً بعودتك. إليك ما يحدث اليوم.',
    generateReport: 'اصدار تقرير',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    progressPerProject: 'التقدم لكل مشروع (%)',
    projectDistribution: 'توزيع المشاريع',
    completed: 'مكتمل',
    active: 'نشط',
    onHold: 'متوقف مؤقتاً',
    activeProjectsStatus: 'حالة المشاريع النشطة',
    viewAll: 'عرض الكل',
    filter: 'تصفية',
    allocatedBudget: 'الميزانية المخصصة',
    exportSchedule: 'تصدير الجدول الزمني',
    baseline: 'خط الأساس للجدول الزمني الرئيسي',
    criticalPath: 'المسار الحرج',
    activityDescription: 'وصف النشاط',
    newDailyReport: 'تقرير يومي جديد',
    siteActivityLog: 'سجل نشاط الموقع',
    totalLabor: 'إجمالي العمالة',
    equipment: 'المعدات',
    deliveries: 'التوريدات',
    ongoingActivities: 'الأنشطة الجارية',
    sitePhotos: 'صور الموقع',
    viewPhoto: 'عرض الصورة',
    pendingApprovals: 'اعتمادات معلقة',
    approve: 'اعتماد',
    review: 'مراجعة',
    createContract: 'إنشاء عقد',
    contractSummary: 'ملخص العقد الرئيسي',
    contractValue: 'قيمة العقد',
    duration: 'المدة',
    variationsClaims: 'أوامر التغيير والمطالبات',
    newInspection: 'تفتيش جديد',
    ncrId: 'رقم NCR',
    description: 'الوصف',
    severity: 'الخطورة',
    dateOpened: 'تاريخ الفتح',
    reportIncident: 'بلاغ عن حادث',
    safeWorkingDays: 'أيام عمل آمنة',
    ltis: 'إصابات الوقت الضائع (LTIs)',
    toolboxTalks: 'اجتماعات السلامة هذا الشهر',
    recentSafetyObs: 'ملاحظات السلامة الأخيرة',
    safetyPerformance: 'أداء السلامة (معدل تكرار LTI)',
    frequencyRate: 'معدل التكرار',
    targetRate: 'المعدل المستهدف',
    months: ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
    docTitle: 'عنوان المستند',
    docCode: 'كود المستند',
    version: 'الإصدار',
    date: 'التاريخ',
    actions: 'الإجراءات',
    actualCost: 'التكلفة الفعلية',
    plannedCost: 'التكلفة المخططة',
    variance: 'الانحراف',
    employee: 'الموظف',
    hours: 'الساعات',
    save: 'حفظ',
    cancel: 'إلغاء',
    projectCode: 'كود المشروع',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    userManagement: 'إدارة المستخدمين',
    role: 'الدور',
    email: 'البريد الإلكتروني',
    addNew: 'إضافة جديد',
    high: 'عالية',
    medium: 'متوسطة',
    low: 'منخفضة'
  }
};

export const MENU_ITEMS = [
  { id: 'dashboard', icon: <LayoutDashboard size={20} />, labelKey: 'dashboard' },
  { id: 'projects', icon: <Briefcase size={20} />, labelKey: 'projects' },
  { id: 'contracts', icon: <FileText size={20} />, labelKey: 'contracts' },
  { id: 'planning', icon: <Calendar size={20} />, labelKey: 'planning' },
  { id: 'site', icon: <HardHat size={20} />, labelKey: 'siteManagement' },
  { id: 'quality', icon: <ShieldCheck size={20} />, labelKey: 'quality' },
  { id: 'safety', icon: <ShieldAlert size={20} />, labelKey: 'safety' },
  { id: 'documents', icon: <Files size={20} />, labelKey: 'documents' },
  { id: 'costs', icon: <DollarSign size={20} />, labelKey: 'costs' },
  { id: 'timesheets', icon: <Clock size={20} />, labelKey: 'timesheets' },
  { id: 'audit', icon: <Activity size={20} />, labelKey: 'audit' },
  { id: 'settings', icon: <Settings size={20} />, labelKey: 'settings' },
];
